development:
  adapter: postgresql
  encoding: unicode
  database: coderbacon_development
  pool: 5
  username: Justin
  timeout: 5000

test:
  adapter: postgresql
  encoding: unicode
  database: coderbacon_test
  pool: 5
  username: Justin
  timeout: 5000