development:
  adapter: postgresql
  encoding: unicode
  database: coderbacon_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  encoding: unicode
  database: coderbacon_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  encoding: unicode
  database: coderbacon_prod
  pool: 5
  timeout: 5000